version: "3"
services: 
    travel_map:
        image: travel_map
        container_name: travel_map
        build: ./travel_map
        ports:
            - "8001:80"
        volumes: 
            - ./travel_map/app:/var/www/html/app
            - ./travel_map/config:/var/www/html/config
            - ./travel_map/apache_logs:/var/log/apache2
        networks: 
            - travel_map_net
        # debug用(dockerfileでapache起動させているのでここでは削除してもＯＫ)
        command: bash -c 'chmod -R 777 /var/www/html/app; /usr/sbin/httpd -DFOREGROUND'
        # ここまで
    db:
        image: mariadb:10.5.6-focal
        restart: always
        container_name: travel_map_db
        networks:
            - travel_map_net
        volumes:
            - ./db/data:/var/lib/mysql
            - ./db/initdb.d:/docker-entrypoint-initdb.d
        environment: 
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=travel_map_db
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
    adminer:
        image: adminer:4.7.7-standalone
        restart: always
        container_name: travel_map_adminer
        ports:
            - "8081:8080"
        networks:
            - travel_map_net
networks: 
    travel_map_net:
        driver: bridge