version: "3"
services: 
    travel_map:
        image: travel_map
        container_name: travel_map
        build: ./travel_map
        ports: 8089:80
        volumes: 
            - ./travel_map/app:/var/www/html
            - ./travel_map/apache_logs:/var/log/apache2
    db:
        image: mariadb
        restart: always
        container_name: travel_map_db
        ports:
            - "3366:3306"
        networks:
            - travel_map_net
        # ボリュームマウント
        volumes:
            - ./db/data:/var/lib/mysql
            - ./db/initdb.d:/docker-entrypoint-initdb.d
        environment: 
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=travel_map_db
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
    adminer:
        image: adminer
        restart: always
        container_name: travel_map_adminer
        ports:
            - "8088:8080"
        networks:
            - travel_map_net
networks: 
    travel_map_net:
        driver: bridge