version: "3"
services: 
    db:
        image: mariadb
        restart: always
        container_name: travel_map_db
        ports:
            - "3366:3306"
        networks:
            - travel_map_net
        volumes:
            - ./db/data:/var/lib/mysql
            - ./db/initdb.d:/docker-entrypoint-initdb.d
        environment: 
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=travel_map_db
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
    adminer:
        image: adminer
        restart: always
        container_name: travel_map_adminer
        ports:
            - "8088:8080"
        networks:
            - travel_map_net
        networks: 
            travel_map_net:
                driver: bridge